### ISSUE TITLE
Steps to generate a debian package from 375-xenial nvidia source code

### ISSUE THREAD

**Issue by muralimk51** [tseliot/nvidia-graphics-drivers#11]
Hi,

I cloned nvidia-graphics -driver from [https://github.com/tseliot/nvidia-graphics-drivers.git]
and checkout to 375-xenial branch.

Could you please let me know How can I generate a debian package like "nvidia-375_375.66-0ubuntu0.16.04.1_amd64.deb" from the above source code.

Could you please let me know what are steps I need to perform to generate a debian.

**Comment by tseliot** [comment]
You can follow this guide: https://www.debian.org/doc/manuals/maint-guide/build.en.html
