### ISSUE TITLE
compute-utils requires libnvidia-cfg1

### ISSUE THREAD

**Issue by jelmd** [tseliot/nvidia-graphics-drivers#29]
nvidia-persistenced (compute-utils) does not work w/o libnvidia-cfg1! Install nvidia-headless on a clean system to check ...

**Comment by tseliot** [comment]
I have just added the dependency in commit  4e9dc7aa98dd21d5ea93a396d1e064128d183240 of the 430-ppa branch. I'll make sure this also gets into the archive.

Thanks for reporting the problem.
