### ISSUE TITLE
ubuntu-drivers installs NFB branch instead of PB

### ISSUE THREAD

**Issue by os369510** [tseliot/nvidia-graphics-drivers#56]
nvidia-driver-530 will be installed instead of nvidia-driver-525 but 530 is NFB and 525 is PB
https://www.nvidia.com/download/driverResults.aspx/199989/en-us/

**Comment by tseliot** [comment]
Hi, I am going to replace 530 with the 535 series very soon. Would this be enough?

**Comment by os369510** [comment]
nv-530 has been transited to nv-535, closed.
